USE DATABASE DATAFABLES;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS FACTS (
  TOPIC      VARCHAR(100),
  FACT       TEXT,
  SOURCE     VARCHAR(255),
  AGE_GROUP  VARCHAR(10)
);

INSERT INTO FACTS (TOPIC, FACT, SOURCE, AGE_GROUP) VALUES
('dolphins', 'Dolphins sleep with one eye open so they can watch for danger.', 'National Geographic', 'all'),
('dolphins', 'A group of dolphins is called a pod, and they work together to catch fish.', 'Britannica Kids', 'all'),
('dolphins', 'Dolphins make clicking sounds to find food — this is called echolocation.', 'NOAA', 'all'),
('dolphins', 'Baby dolphins are called calves and stay with their mothers for up to six years.', 'National Geographic', 'all'),
('dolphins', 'Dolphins can recognize themselves in a mirror, which shows they are self-aware.', 'Scientific American', '8-10'),
('dolphins', 'Bottlenose dolphins can swim up to 22 miles per hour.', 'NOAA', 'all'),
('dolphins', 'Dolphins breathe air through a blowhole on top of their head.', 'Britannica Kids', '5-7'),
('dolphins', 'Dolphins have been observed teaching their young to use tools, like sponges to protect their snouts while foraging.', 'National Geographic', '11-13'),
('space', 'One million Earths could fit inside the Sun.', 'NASA', 'all'),
('space', 'Footprints on the Moon will stay there for millions of years because there is no wind.', 'NASA', 'all'),
('space', 'Saturn''s rings are made mostly of ice and rock, and are only about 30 feet thick in some places.', 'NASA', 'all'),
('space', 'A day on Venus is longer than a year on Venus.', 'NASA', '8-10'),
('space', 'The Sun is so big that about 1.3 million Earths could fit inside it.', 'NASA', '5-7'),
('space', 'There are more stars in the universe than grains of sand on all of Earth''s beaches.', 'NASA', 'all'),
('space', 'The International Space Station travels around Earth at 17,500 miles per hour.', 'NASA', '8-10'),
('space', 'Light from the Sun takes about 8 minutes to reach Earth.', 'NASA', '8-10'),
('space', 'Neutron stars are so dense that a teaspoon of their material would weigh about a billion tons.', 'NASA', '11-13'),
('ocean', 'The ocean covers more than 70% of Earth''s surface.', 'NOAA', 'all'),
('ocean', 'The deepest part of the ocean is called the Mariana Trench — it is deeper than Mount Everest is tall.', 'NOAA', 'all'),
('ocean', 'Tiny ocean plants called phytoplankton produce more than half of Earth''s oxygen.', 'NOAA', '8-10'),
('ocean', 'More than 80% of the ocean has never been explored by humans.', 'NOAA', 'all'),
('ocean', 'The ocean is home to the largest animal on Earth — the blue whale.', 'National Geographic', '5-7'),
('ocean', 'Coral reefs are sometimes called the rainforests of the sea because so many animals live there.', 'NOAA', 'all'),
('ocean', 'Seahorses are the only animal where the father carries and gives birth to the babies.', 'National Geographic', 'all'),
('ocean', 'The ocean absorbs about 30% of the carbon dioxide produced by humans, helping to slow climate change.', 'NOAA', '11-13'),
('dinosaurs', 'Birds are actually living dinosaurs — they evolved from feathered theropod dinosaurs.', 'Smithsonian', 'all'),
('dinosaurs', 'The T. rex had the strongest bite of any land animal that ever lived.', 'Smithsonian', 'all'),
('dinosaurs', 'Some dinosaurs were smaller than a chicken!', 'Natural History Museum', '5-7'),
('dinosaurs', 'Dinosaurs lived on Earth for about 165 million years.', 'Smithsonian', 'all'),
('dinosaurs', 'The longest dinosaur was the Argentinosaurus, which was about 100 feet long.', 'Natural History Museum', '8-10'),
('dinosaurs', 'Paleontologists have found dinosaur fossils on every continent, including Antarctica.', 'Smithsonian', '8-10'),
('dinosaurs', 'The word "dinosaur" means "terrible lizard" in Greek.', 'Britannica Kids', 'all'),
('dinosaurs', 'An asteroid about 6 miles wide caused the mass extinction of non-bird dinosaurs 66 million years ago.', 'NASA', '11-13'),
('weather', 'Lightning strikes Earth about 100 times every second.', 'NOAA', 'all'),
('weather', 'A single snowflake can take up to an hour to fall from a cloud to the ground.', 'NOAA', 'all'),
('weather', 'Tornadoes can spin faster than 300 miles per hour.', 'NOAA', '8-10'),
('weather', 'Raindrops are not teardrop-shaped — they are actually round, like tiny balls.', 'NOAA', 'all'),
('weather', 'The coldest temperature ever recorded on Earth was -128.6 degrees Fahrenheit in Antarctica.', 'NOAA', '8-10'),
('weather', 'A hurricane can release as much energy in one day as half of the world''s electricity for a year.', 'NOAA', '11-13'),
('weather', 'Fog is just a cloud that forms very close to the ground.', 'NOAA', '5-7'),
('weather', 'No two snowflakes are exactly alike because each forms a unique path through the atmosphere.', 'NOAA', 'all'),
('plants', 'Trees communicate through underground networks of fungi, sometimes called the Wood Wide Web.', 'Smithsonian', '8-10'),
('plants', 'Some plants, like the Venus flytrap, catch and eat insects for nutrients.', 'Britannica Kids', 'all'),
('plants', 'The oldest living tree on Earth is over 5,000 years old and grows in California.', 'National Geographic', 'all'),
('plants', 'Bamboo is the fastest-growing plant on Earth — it can grow 35 inches in just one day.', 'Smithsonian', 'all'),
('plants', 'Plants make their own food using sunlight, water, and air in a process called photosynthesis.', 'Britannica Kids', '5-7'),
('plants', 'The Amazon Rainforest produces about 20% of the world''s oxygen.', 'National Geographic', '8-10'),
('plants', 'A single oak tree can produce about 70,000 acorns in a year.', 'Smithsonian', '8-10'),
('plants', 'Sunflowers always face the sun — this movement is called heliotropism.', 'Britannica Kids', 'all'),
('animals', 'Octopuses have three hearts and blue blood.', 'National Geographic', 'all'),
('animals', 'A group of flamingos is called a flamboyance.', 'Britannica Kids', 'all'),
('animals', 'Elephants are the only mammals that cannot jump.', 'National Geographic', 'all'),
('animals', 'A snail can sleep for up to three years when the weather is too hot or dry.', 'Smithsonian', 'all'),
('animals', 'Crows are one of the smartest animals — they can recognize human faces and use tools.', 'National Geographic', '8-10'),
('animals', 'A group of cats is called a clowder, and a group of kittens is called a kindle.', 'Britannica Kids', 'all'),
('animals', 'Honey never spoils — archaeologists found 3,000-year-old honey in Egyptian tombs that was still edible.', 'Smithsonian', '8-10'),
('animals', 'The mantis shrimp can punch with the speed of a bullet and sees 16 types of color.', 'Smithsonian', '11-13'),
('robots', 'The word robot comes from a Czech word meaning forced labor.', 'Smithsonian', 'all'),
('robots', 'NASA''s Perseverance rover is exploring the surface of Mars right now.', 'NASA', 'all'),
('robots', 'Robots are used in surgery to help doctors make very tiny, precise movements.', 'Britannica Kids', '8-10'),
('robots', 'The first industrial robot was installed in a General Motors factory in 1961.', 'Smithsonian', '8-10'),
('robots', 'There are robots that can do backflips, run, and even dance.', 'Britannica Kids', '5-7'),
('robots', 'Self-driving cars use sensors and AI to see the road, similar to how humans use their eyes.', 'Britannica Kids', '8-10'),
('robots', 'Some robots are modeled after animals — there are snake robots, fish robots, and bee-sized drones.', 'National Geographic', '8-10'),
('robots', 'The Mars rovers have driven a combined total of more than 50 kilometers on the surface of Mars.', 'NASA', '11-13'),
('volcanoes', 'There are about 1,500 potentially active volcanoes on Earth.', 'USGS', 'all'),
('volcanoes', 'Lava can reach temperatures of 2,200 degrees Fahrenheit — hot enough to melt rock.', 'USGS', 'all'),
('volcanoes', 'The largest volcano in the solar system is Olympus Mons on Mars, three times taller than Mount Everest.', 'NASA', '8-10'),
('volcanoes', 'Volcanic eruptions created many of Earth''s islands, including the Hawaiian Islands.', 'USGS', 'all'),
('volcanoes', 'Volcanoes can also erupt underwater — these are called submarine volcanoes.', 'NOAA', '8-10'),
('volcanoes', 'Volcanic ash can travel thousands of miles and affect weather patterns around the world.', 'USGS', '11-13'),
('volcanoes', 'Pumice is a volcanic rock so full of air bubbles that it can float on water.', 'USGS', 'all'),
('volcanoes', 'The eruption of Mount Tambora in 1815 caused a year without summer around the world.', 'Smithsonian', '11-13'),
('egypt', 'Ancient Egyptians invented one of the first writing systems, called hieroglyphics.', 'Smithsonian', 'all'),
('egypt', 'The Great Pyramid of Giza was the tallest human-made structure in the world for over 3,800 years.', 'Smithsonian', 'all'),
('egypt', 'Ancient Egyptians had over 2,000 gods and goddesses.', 'Britannica Kids', '8-10'),
('egypt', 'Cats were sacred in ancient Egypt — harming one was considered a serious crime.', 'Smithsonian', 'all'),
('egypt', 'Ancient Egyptians used a 365-day calendar, similar to the one we use today.', 'Smithsonian', '8-10'),
('egypt', 'The Sphinx of Giza was carved from a single block of limestone and is about 4,500 years old.', 'Smithsonian', '8-10'),
('egypt', 'Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.', 'Smithsonian', '11-13'),
('egypt', 'Ancient Egyptians used toothpaste made from crushed eggshells, ashes, and salt.', 'Smithsonian', 'all'),
('ancient egypt', 'Ancient Egyptians invented one of the first writing systems, called hieroglyphics.', 'Smithsonian', 'all'),
('ancient egypt', 'The Great Pyramid of Giza was the tallest human-made structure in the world for over 3,800 years.', 'Smithsonian', 'all'),
('ancient egypt', 'Cats were sacred in ancient Egypt — harming one was considered a serious crime.', 'Smithsonian', 'all'),
('ancient egypt', 'Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.', 'Smithsonian', '11-13'),
('science', 'Humans share about 60% of their DNA with bananas.', 'Smithsonian', 'all'),
('science', 'The human brain generates about 20 watts of power — enough to power a dim light bulb.', 'Britannica Kids', '8-10'),
('science', 'Water expands when it freezes, which is why ice floats instead of sinking.', 'Britannica Kids', '8-10'),
('science', 'Sound travels about four times faster through water than through air.', 'Britannica Kids', '8-10'),
('science', 'Your body has about 37 trillion cells, each doing a special job.', 'Smithsonian', 'all'),
('science', 'Atoms are so tiny that millions of them could fit on the period at the end of this sentence.', 'Britannica Kids', '8-10'),
('science', 'The human nose can detect over one trillion different smells.', 'Smithsonian', '8-10'),
('science', 'Glass is actually a very slow-moving liquid — it just moves too slowly for us to see.', 'Smithsonian', '11-13'),
('history', 'The printing press, invented around 1440, helped spread books and knowledge to millions of people.', 'Smithsonian', 'all'),
('history', 'Ancient Romans used to brush their teeth with powdered charcoal and crushed bones.', 'Smithsonian', '8-10'),
('history', 'The Great Wall of China took over 1,000 years to fully build.', 'Smithsonian', 'all'),
('history', 'Vikings were the first Europeans to reach North America, about 500 years before Columbus.', 'Smithsonian', '8-10'),
('history', 'The first Olympic Games were held in ancient Greece in 776 BC.', 'Smithsonian', 'all'),
('history', 'The Library of Alexandria in ancient Egypt was once the largest library in the world.', 'Smithsonian', '8-10'),
('history', 'The shortest war in history lasted only 38 minutes — between Britain and Zanzibar in 1896.', 'Smithsonian', '11-13'),
('history', 'The first person to walk on the Moon was Neil Armstrong on July 20, 1969.', 'NASA', '5-7'),
('math', 'Zero is the only number that cannot be represented by Roman numerals.', 'Britannica Kids', 'all'),
('math', 'A googol is the number 1 followed by 100 zeros — bigger than the number of atoms in the universe.', 'Britannica Kids', '8-10'),
('math', 'The Fibonacci sequence appears all over nature — in sunflowers, pinecones, and seashells.', 'Smithsonian', '8-10'),
('math', 'Pi goes on forever — it has been calculated to over 100 trillion decimal places.', 'Britannica Kids', '8-10'),
('math', 'A shape with infinite sides is called a circle.', 'Britannica Kids', '5-7'),
('math', 'The equals sign was invented in 1557 by a Welsh mathematician named Robert Recorde.', 'Smithsonian', '8-10'),
('math', 'If you fold a piece of paper 42 times, the stack would reach from Earth to the Moon.', 'Smithsonian', 'all'),
('math', 'Prime numbers — numbers only divisible by 1 and themselves — go on forever with no end.', 'Britannica Kids', '11-13'),
('music', 'Music has been found in every human culture throughout history.', 'Smithsonian', 'all'),
('music', 'Playing a musical instrument uses almost every part of the brain at the same time.', 'Smithsonian', '8-10'),
('music', 'The world''s oldest known musical instrument is a flute made from bone, about 60,000 years old.', 'Smithsonian', '8-10'),
('music', 'Fast music can make you feel more energetic, while slow music can calm your heartbeat.', 'Smithsonian', 'all'),
('music', 'Beethoven composed some of his greatest music after he became completely deaf.', 'Smithsonian', '8-10'),
('music', 'The piano has 88 keys and over 12,000 individual parts inside it.', 'Britannica Kids', '8-10'),
('music', 'Listening to music releases dopamine in the brain — the same chemical that makes you feel happy.', 'Smithsonian', '11-13'),
('sharks', 'Sharks have been on Earth for over 450 million years — before trees even existed.', 'NOAA', 'all'),
('sharks', 'Sharks have to keep swimming to breathe — they need water flowing through their gills.', 'NOAA', '5-7'),
('sharks', 'A shark can grow tens of thousands of teeth in its lifetime — they regrow them constantly.', 'National Geographic', 'all'),
('sharks', 'The whale shark is the biggest fish in the ocean but only eats tiny plankton.', 'NOAA', 'all'),
('sharks', 'Sharks have special sensors that detect electrical fields from other animals.', 'NOAA', '11-13'),
('sharks', 'Most sharks are not dangerous to humans — only about 3 species are responsible for most attacks.', 'NOAA', '8-10'),
('butterflies', 'Butterflies taste with their feet — they have taste sensors on their legs.', 'Smithsonian', 'all'),
('butterflies', 'A butterfly begins life as an egg, becomes a caterpillar, wraps into a chrysalis, then emerges as a butterfly.', 'Britannica Kids', '5-7'),
('butterflies', 'The monarch butterfly migrates up to 3,000 miles from Canada to Mexico every year.', 'National Geographic', 'all'),
('butterflies', 'Butterfly wings are covered in tiny scales made from the same material as human hair and nails.', 'Smithsonian', '8-10'),
('butterflies', 'Some butterflies can fly up to 25 miles per hour.', 'National Geographic', 'all'),
('butterflies', 'A group of butterflies is called a kaleidoscope.', 'Britannica Kids', 'all'),
('rainforest', 'Rainforests cover only 6% of Earth''s surface but are home to more than half of the world''s species.', 'National Geographic', 'all'),
('rainforest', 'The Amazon River releases so much fresh water you can taste it 100 miles out into the Atlantic Ocean.', 'NOAA', '8-10'),
('rainforest', 'A single rainforest tree can be home to hundreds of species of insects, birds, and plants.', 'National Geographic', 'all'),
('rainforest', 'Many medicines, including aspirin, were originally discovered in rainforest plants.', 'Smithsonian', '8-10'),
('rainforest', 'The Amazon Rainforest is so large it creates its own weather and rainfall.', 'National Geographic', '11-13'),
('human body', 'Your heart beats about 100,000 times every single day.', 'Britannica Kids', 'all'),
('human body', 'Bones are stronger than concrete — a human thigh bone can hold the weight of a car.', 'Smithsonian', 'all'),
('human body', 'You have about 100,000 hairs on your head, and each one grows about 6 inches per year.', 'Britannica Kids', '8-10'),
('human body', 'Your small intestine is about 20 feet long — much longer than you are tall!', 'Britannica Kids', 'all'),
('human body', 'Humans are the only animals that cry emotional tears.', 'Smithsonian', '8-10'),
('human body', 'The brain is about 75% water and uses 20% of your body''s total energy.', 'Smithsonian', '8-10'),
('human body', 'Your eyes can distinguish about 10 million different colors.', 'Smithsonian', '8-10'),
('penguins', 'Penguins are birds but they cannot fly — instead they are expert swimmers.', 'National Geographic', '5-7'),
('penguins', 'Emperor penguins can dive deeper than 1,800 feet and hold their breath for over 20 minutes.', 'National Geographic', 'all'),
('penguins', 'Male emperor penguins keep their egg warm on their feet during the Antarctic winter without eating for months.', 'National Geographic', 'all'),
('penguins', 'A group of penguins in the water is called a raft, and on land it is called a waddle.', 'Britannica Kids', 'all'),
('penguins', 'Penguins have a gland above their eye that converts salt water to fresh water so they can drink from the ocean.', 'National Geographic', '8-10');

SELECT TOPIC, COUNT(*) AS FACT_COUNT FROM FACTS GROUP BY TOPIC ORDER BY TOPIC;
